"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['nmck_bb.ico','tools.py','Ui_checkScore.py','Ui_verifyMail.py']
OPTIONS = {
    'iconfile':'nmck.icns',
    'plist': {
                    'CFBundleName'   : 'Tongji-ScoreAutoGet',     # 应用名
                    'CFBundleDisplayName': '同济成绩自动查询器', # 应用显示名
                    'CFBundleVersion': '0.1.0',      # 应用版本号
                    'CFBundleIdentifier' : 'tongjiScoreAutoGet', # 应用包名、唯一标识
                    'NSHumanReadableCopyright': 'Copyright © 2022 Cinea Works. Use the GPL license.', # 可读版权
                    'includes': ['loguru', 'PyQt5.QtCore', 'PyQt5.QtWidgets', 'PyQt5.QtGui','requests']
                       }
           }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
