# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\算法实验室\17pyqt查成绩\Tongji-AutoGetScore\ui\verifyMail.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(522, 223)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(170, 180, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 301, 61))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 80, 481, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.varifyCodeLE = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.varifyCodeLE.setObjectName("varifyCodeLE")
        self.horizontalLayout.addWidget(self.varifyCodeLE)
        self.resendBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.resendBtn.setEnabled(True)
        self.resendBtn.setCheckable(False)
        self.resendBtn.setObjectName("resendBtn")
        self.horizontalLayout.addWidget(self.resendBtn)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 481, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 481, 21))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.resendBtn.clicked.connect(Dialog.resend)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">请验证您的邮箱</span></p><p>一封含有验证码的邮件已经送出</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "请输入验证码"))
        self.resendBtn.setText(_translate("Dialog", "重新发送"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>开发者不希望本程序被用作骚扰用途，请您谅解</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p>邮箱仅在第一次被填入时需要验证，后续将不再需要验证</p></body></html>"))
